import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const headline = context.query.headlines;

  const request = await fetch(
    `https://newsapi.org/v2${requests[headline]?.url || requests.tesla.url}`
    // "https://newsapi.org/v2/everything?q=tesla&from=2022-07-22&sortBy=publishedAt&apiKey=f044f86ad32f4df3a2f7e13ede1fec97"
  ).then((res) => res.json());

  return {
    props: {
      results: request.articles,
    },
  };
}
